Data Preprocessing involves importing and transforming the data into a usable form. This involves cleaning the data to remove noise, finding missing entries and replace them suitably and much more.

In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [0]:
df = pd.read_csv("/content/Data.csv")

In [74]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

As we can see, the 5th cell in salary's column is NaN and so is age's 7th column. Also, the purchased column has values "Yes" and "No". If we are to use this data, we have to convert it into some form of mathematical notation. 

In [0]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [0]:
x = x.values

In [0]:
y = y.values

In [0]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
x[:,1:3] = imputer.fit_transform(x[:,1:3])

In [79]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")
x = ct.fit_transform(x)

In [81]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [83]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [0]:
dummies = pd.get_dummies(df.Country)
df = pd.concat([df,dummies],axis='columns')
df = df.drop(columns=['Country'])

We can simply use pandas to get dummy variables and perform one hot encoding by using `pd.get_dummies(df.ourcolumn)`. This returns a dataframe that contains no. of columns equal to number of categorical features that we wish to encode.
Each cell has a value 1 if that row in our original df has value equal to the column name

In [0]:
means = df.mean()

In [0]:
df = df.fillna(df.mean())

In [89]:
df

Age        Salary Purchased  France  Germany  Spain
0  44.000000  72000.000000        No       1        0      0
1  27.000000  48000.000000       Yes       0        0      1
2  30.000000  54000.000000        No       0        1      0
3  38.000000  61000.000000        No       0        0      1
4  40.000000  63777.777778       Yes       0        1      0
5  35.000000  58000.000000       Yes       1        0      0
6  38.777778  52000.000000        No       0        0      1
7  48.000000  79000.000000       Yes       1        0      0
8  50.000000  83000.000000        No       0        1      0
9  37.000000  67000.000000       Yes       1        0      0

In [90]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

Two ways of feature scaling are standardization and normalization<br>
standardization = (x-mean(x))/std_dev(x)<br>
x_norm = (x-min(x))/(max(x)-min(x))



In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [92]:
x

array([[ 1.22474487e+00, -6.54653671e-01, -6.54653671e-01,
         7.58874362e-01,  7.49473254e-01],
       [-8.16496581e-01, -6.54653671e-01,  1.52752523e+00,
        -1.71150388e+00, -1.43817841e+00],
       [-8.16496581e-01,  1.52752523e+00, -6.54653671e-01,
        -1.27555478e+00, -8.91265492e-01],
       [-8.16496581e-01, -6.54653671e-01,  1.52752523e+00,
        -1.13023841e-01, -2.53200424e-01],
       [-8.16496581e-01,  1.52752523e+00, -6.54653671e-01,
         1.77608893e-01,  6.63219199e-16],
       [ 1.22474487e+00, -6.54653671e-01, -6.54653671e-01,
        -5.48972942e-01, -5.26656882e-01],
       [-8.16496581e-01, -6.54653671e-01,  1.52752523e+00,
         0.00000000e+00, -1.07356980e+00],
       [ 1.22474487e+00, -6.54653671e-01, -6.54653671e-01,
         1.34013983e+00,  1.38753832e+00],
       [-8.16496581e-01,  1.52752523e+00, -6.54653671e-01,
         1.63077256e+00,  1.75214693e+00],
       [ 1.22474487e+00, -6.54653671e-01, -6.54653671e-01,
        -2.58340208e-01

Train test split

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size = 0.25, random_state = 42)